In [25]:
import pandas as pd
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
import tensorflow as tf
import numpy as np
import streamlit as st
from tensorflow.keras.layers import Normalization,Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.losses import SparseCategoricalCrossentropy,BinaryCrossentropy
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer


In [4]:
df = pd.read_csv("IMDB Dataset.csv")
print(df.head())

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive


In [5]:
lable_encoder = LabelEncoder()
y_train = lable_encoder.fit_transform(df["sentiment"])
print(y_train[:10])

[1 1 1 0 1 1 1 0 0 1]


In [11]:
vec = CountVectorizer(max_features=5000, stop_words='english')
x_train = vec.fit_transform(df["review"]).toarray()


[0 0 0 ... 0 0 0]


In [ ]:
model = Sequential(
    [
        Dense(units=64,activation="relu"),
        Dense(units=32,activation="relu"),
        Dense(units=1,activation="sigmoid")
    ]
)

model.compile(
    loss = BinaryCrossentropy,
    optimizer = tf.keras.optimizers.Adam(learning_rate = 0.001)
)

model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 0.3680
Epoch 2/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 0.2034
Epoch 3/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 0.1142
Epoch 4/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 0.0420
Epoch 5/5
1347/1563 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0154

In [49]:
x_test = ["I will say it as a Greatest movie of all time "]
x_test_vec = vec.transform(x_test).toarray()
print(x_test_vec)

[[0 0 0 ... 0 0 0]]


In [51]:
prediction = model.predict(x_test_vec)
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
[[0.99873686]]
